api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonhal:
            mime_types:
                - application/hal+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html

